name: anysql
description: A unified Dart database abstraction, setup generator, and driver layer for SQL and NoSQL databases.
version: 0.2.0
repository: https://github.com/Azrul16/anysql
issue_tracker: https://github.com/Azrul16/anysql/issues
topics:
  - database
  - sql
  - nosql
  - cli
  - configuration

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.11.4

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.0

executables:
  anysql:

dependencies:
  mongo_dart: ^0.10.8
  mysql_client: ^0.0.27
  postgres: ^3.5.9
  shelf: ^1.4.2
  sqlite3: ^3.3.1
