name: anysql
description: A unified Dart database abstraction and setup generator for SQL and NoSQL drivers.
version: 0.1.1
repository: https://github.com/Azrul16/anysql
issue_tracker: https://github.com/Azrul16/anysql/issues
topics:
  - database
  - sql
  - nosql
  - cli
  - configuration

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.11.4

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.0

executables:
  anysql:
