import 'anysql_config.dart';

final class AnySqlSetupInput {
  const AnySqlSetupInput({
    required this.dialect,
    required this.database,
    this.host,
    this.port,
    this.username,
    this.passwordEnvironmentKey,
    this.sslEnabled = false,
    this.backendUrl,
    this.backendHeaders = const {},
    this.className = 'DefaultAnySqlOptions',
  });

  final AnySqlDialect dialect;
  final String database;
  final String? host;
  final int? port;
  final String? username;
  final String? passwordEnvironmentKey;
  final bool sslEnabled;
  final String? backendUrl;
  final Map<String, String> backendHeaders;
  final String className;
}

String generateAnySqlOptionsFile(AnySqlSetupInput input) {
  final constructor = _configConstructor(input);
  final backendUri = input.backendUrl == null
      ? 'null'
      : "Uri.parse('${_escape(input.backendUrl!)}')";
  final backendHeaders = _stringMapLiteral(input.backendHeaders);

  return '''
// Generated by `dart run anysql configure`.
// Do not commit real database passwords. Prefer --password-env with --dart-define.

import 'package:anysql/anysql.dart';

final class ${input.className} {
  const ${input.className}._();

  static AnySqlOptions get current => AnySqlOptions(
        config: config,
        backendUri: backendUri,
        backendHeaders: backendHeaders,
      );

  static AnySqlConfig get config => $constructor;

  static Uri? get backendUri => $backendUri;

  static Map<String, String> get backendHeaders => $backendHeaders;

  static AnySqlDialect get dialect => config.dialect;

  static Future<AnySqlConnection> connect({
    required AnySqlDriver driver,
  }) {
    return current.connect(driver: driver);
  }

  static Future<AnySqlStore> connectStore({
    required AnySqlDriver driver,
  }) async {
    final connection = await connect(driver: driver);
    return connection.store(dialect: dialect);
  }

  static Future<T> withStore<T>({
    required AnySqlDriver driver,
    required Future<T> Function(AnySqlStore store) action,
  }) async {
    final store = await connectStore(driver: driver);
    try {
      return await action(store);
    } finally {
      await store.close();
    }
  }

  static Future<AnySqlConnection> openWith(AnySql anySql) {
    return current.openWith(anySql);
  }

  static Future<AnySqlConnection> connectBackend({
    required AnySqlBackendClient client,
  }) {
    return current.connectBackend(client: client);
  }

  static Future<AnySqlStore> connectBackendStore({
    required AnySqlBackendClient client,
  }) async {
    final connection = await connectBackend(client: client);
    return connection.store(dialect: dialect);
  }

  static Future<T> withBackendStore<T>({
    required AnySqlBackendClient client,
    required Future<T> Function(AnySqlStore store) action,
  }) async {
    final store = await connectBackendStore(client: client);
    try {
      return await action(store);
    } finally {
      await store.close();
    }
  }
}
''';
}

String generateAnySqlSampleOptionsFile({
  String className = 'AnySqlOptionsFile',
}) {
  return '''
// Generated by `dart run anysql init`.
// Replace these sample values with your own database or backend settings.
// Do not commit real database passwords. Prefer --dart-define values.

import 'package:anysql/anysql.dart';

final class $className {
  const $className._();

  static AnySqlOptions get postgres => AnySqlOptions(
        config: AnySqlConfig.postgres(
          host: 'localhost',
          port: 5432,
          database: 'postgres_database',
          username: 'postgres_user',
          password: const String.fromEnvironment('ANYSQL_POSTGRES_PASSWORD'),
          sslEnabled: false,
        ),
        backendUri: Uri.parse('https://api.example.com/anysql/postgres'),
        backendHeaders: const {'x-client': 'anysql-postgres'},
      );

  static AnySqlOptions get mysql => AnySqlOptions(
        config: AnySqlConfig.mysql(
          host: 'localhost',
          port: 3306,
          database: 'mysql_database',
          username: 'mysql_user',
          password: const String.fromEnvironment('ANYSQL_MYSQL_PASSWORD'),
          sslEnabled: false,
        ),
        backendUri: Uri.parse('https://api.example.com/anysql/mysql'),
        backendHeaders: const {'x-client': 'anysql-mysql'},
      );

  static AnySqlOptions get sqlite => AnySqlOptions(
        config: AnySqlConfig.sqlite(
          database: 'app_database.sqlite',
        ),
        backendUri: Uri.parse('https://api.example.com/anysql/sqlite'),
        backendHeaders: const {'x-client': 'anysql-sqlite'},
      );

  static AnySqlOptions get mongodb => AnySqlOptions(
        config: AnySqlConfig.mongodb(
          host: 'localhost',
          port: 27017,
          database: 'mongodb_database',
          username: 'mongodb_user',
          password: const String.fromEnvironment('ANYSQL_MONGODB_PASSWORD'),
          sslEnabled: false,
        ),
        backendUri: Uri.parse('https://api.example.com/anysql/mongodb'),
        backendHeaders: const {'x-client': 'anysql-mongodb'},
      );

  static Map<AnySqlDialect, AnySqlOptions> get all => {
        AnySqlDialect.postgres: postgres,
        AnySqlDialect.mysql: mysql,
        AnySqlDialect.sqlite: sqlite,
        AnySqlDialect.mongodb: mongodb,
      };

  static AnySqlOptions byDialect(AnySqlDialect dialect) {
    final options = all[dialect];
    if (options == null) {
      throw AnySqlException('No sample options for \${dialect.name}.');
    }

    return options;
  }
}
''';
}

String generateAnySqlFirebaseStyleOptionsFile(AnySqlSetupInput input) {
  final placeholderInput = _placeholderInput(input);
  final contents = generateAnySqlOptionsFile(placeholderInput);
  final editHint = input.dialect == AnySqlDialect.sqlite
      ? 'Edit the generated values for your sqlite database.'
      : 'Edit the TODO values for your ${input.dialect.name} database.';

  return contents.replaceFirst(
    '// Generated by `dart run anysql configure`.\n'
        '// Do not commit real database passwords. Prefer --password-env with --dart-define.',
    '// Generated by `dart run anysql`.\n'
        '// $editHint\n'
        '// For Flutter apps, prefer connectBackendStore with a secure backend API.',
  );
}

String _configConstructor(AnySqlSetupInput input) {
  final values = switch (input.dialect) {
    AnySqlDialect.sqlite => <String>[
      _stringArgument('database', input.database),
    ],
    AnySqlDialect.custom => <String>[
      'dialect: AnySqlDialect.custom',
      if (input.host != null) _stringArgument('host', input.host!),
      if (input.port != null) 'port: ${input.port}',
      _stringArgument('database', input.database),
      if (input.username != null) _stringArgument('username', input.username!),
      if (input.passwordEnvironmentKey != null)
        "password: const String.fromEnvironment('${_escape(input.passwordEnvironmentKey!)}')",
      if (input.sslEnabled) 'sslEnabled: true',
    ],
    _ => <String>[
      if (input.host != null) _stringArgument('host', input.host!),
      if (input.port != null) 'port: ${input.port}',
      _stringArgument('database', input.database),
      if (input.username != null) _stringArgument('username', input.username!),
      if (input.passwordEnvironmentKey != null)
        "password: const String.fromEnvironment('${_escape(input.passwordEnvironmentKey!)}')",
      if (input.sslEnabled) 'sslEnabled: true',
    ],
  };

  final constructor = input.dialect == AnySqlDialect.custom
      ? 'AnySqlConfig'
      : 'AnySqlConfig.${input.dialect.name}';

  return '$constructor(\n'
      '          ${values.join(',\n          ')},\n'
      '        )';
}

AnySqlSetupInput _placeholderInput(AnySqlSetupInput input) {
  final database = switch (input.dialect) {
    AnySqlDialect.sqlite => 'app.sqlite',
    AnySqlDialect.postgres => 'TODO_POSTGRES_DATABASE',
    AnySqlDialect.mysql => 'TODO_MYSQL_DATABASE',
    AnySqlDialect.mongodb => 'TODO_MONGODB_DATABASE',
    AnySqlDialect.custom => 'TODO_DATABASE',
  };
  final username = switch (input.dialect) {
    AnySqlDialect.sqlite => null,
    AnySqlDialect.postgres => 'TODO_POSTGRES_USERNAME',
    AnySqlDialect.mysql => 'TODO_MYSQL_USERNAME',
    AnySqlDialect.mongodb => 'TODO_MONGODB_USERNAME',
    AnySqlDialect.custom => 'TODO_USERNAME',
  };

  return AnySqlSetupInput(
    dialect: input.dialect,
    host: input.dialect == AnySqlDialect.sqlite ? null : 'localhost',
    port: input.dialect == AnySqlDialect.sqlite
        ? null
        : _defaultPort(input.dialect),
    database: database,
    username: username,
    passwordEnvironmentKey: input.dialect == AnySqlDialect.sqlite
        ? null
        : _defaultPasswordKey(input.dialect),
    sslEnabled: false,
    backendUrl: input.backendUrl ?? 'https://api.example.com/anysql',
    backendHeaders: input.backendHeaders,
    className: input.className,
  );
}

int? _defaultPort(AnySqlDialect dialect) {
  return switch (dialect) {
    AnySqlDialect.postgres => 5432,
    AnySqlDialect.mysql => 3306,
    AnySqlDialect.mongodb => 27017,
    AnySqlDialect.sqlite || AnySqlDialect.custom => null,
  };
}

String? _defaultPasswordKey(AnySqlDialect dialect) {
  return switch (dialect) {
    AnySqlDialect.postgres => 'ANYSQL_POSTGRES_PASSWORD',
    AnySqlDialect.mysql => 'ANYSQL_MYSQL_PASSWORD',
    AnySqlDialect.mongodb => 'ANYSQL_MONGODB_PASSWORD',
    AnySqlDialect.sqlite || AnySqlDialect.custom => null,
  };
}

String _stringArgument(String name, String value) {
  final literal = "'${_escape(value)}'";
  if (value.startsWith('TODO_')) {
    return '$name: $literal, // TODO: replace with your value';
  }

  return '$name: $literal';
}

String _escape(String value) {
  final buffer = StringBuffer();

  for (final codeUnit in value.codeUnits) {
    switch (codeUnit) {
      case 0x08:
        buffer.write(r'\b');
      case 0x09:
        buffer.write(r'\t');
      case 0x0A:
        buffer.write(r'\n');
      case 0x0B:
        buffer.write(r'\v');
      case 0x0C:
        buffer.write(r'\f');
      case 0x0D:
        buffer.write(r'\r');
      case 0x24:
        buffer.write(r'\$');
      case 0x27:
        buffer.write(r"\'");
      case 0x5C:
        buffer.write(r'\\');
      default:
        if (codeUnit < 0x20) {
          buffer.write(r'\x');
          buffer.write(codeUnit.toRadixString(16).padLeft(2, '0'));
        } else {
          buffer.writeCharCode(codeUnit);
        }
    }
  }

  return buffer.toString();
}

String _stringMapLiteral(Map<String, String> values) {
  if (values.isEmpty) {
    return 'const {}';
  }

  final entries = values.entries.map(
    (entry) => "'${_escape(entry.key)}': '${_escape(entry.value)}'",
  );
  return 'const {${entries.join(', ')}}';
}
