import 'anysql_config.dart';

final class AnySqlSetupInput {
  const AnySqlSetupInput({
    required this.dialect,
    required this.database,
    this.host,
    this.port,
    this.username,
    this.passwordEnvironmentKey,
    this.sslEnabled = false,
    this.backendUrl,
    this.backendHeaders = const {},
    this.className = 'DefaultAnySqlOptions',
  });

  final AnySqlDialect dialect;
  final String database;
  final String? host;
  final int? port;
  final String? username;
  final String? passwordEnvironmentKey;
  final bool sslEnabled;
  final String? backendUrl;
  final Map<String, String> backendHeaders;
  final String className;
}

String generateAnySqlOptionsFile(AnySqlSetupInput input) {
  final constructor = _configConstructor(input);
  final backendUri = input.backendUrl == null
      ? 'null'
      : "Uri.parse('${_escape(input.backendUrl!)}')";
  final backendHeaders = _stringMapLiteral(input.backendHeaders);

  return '''
// Generated by `dart run anysql configure`.
// Do not commit real database passwords. Prefer --password-env with --dart-define.

import 'package:anysql/anysql.dart';

final class ${input.className} {
  const ${input.className}._();

  static AnySqlOptions get current => AnySqlOptions(
        config: config,
        backendUri: backendUri,
        backendHeaders: backendHeaders,
      );

  static AnySqlConfig get config => $constructor;

  static Uri? get backendUri => $backendUri;

  static Map<String, String> get backendHeaders => $backendHeaders;

  static Future<AnySqlConnection> connect({
    required AnySqlDriver driver,
  }) {
    return current.connect(driver: driver);
  }

  static Future<AnySqlConnection> openWith(AnySql anySql) {
    return current.openWith(anySql);
  }

  static Future<AnySqlConnection> connectBackend({
    required AnySqlBackendClient client,
  }) {
    return current.connectBackend(client: client);
  }
}
''';
}

String _configConstructor(AnySqlSetupInput input) {
  final values = <String>[
    if (input.host != null) "host: '${_escape(input.host!)}'",
    if (input.port != null) 'port: ${input.port}',
    "database: '${_escape(input.database)}'",
    if (input.username != null) "username: '${_escape(input.username!)}'",
    if (input.passwordEnvironmentKey != null)
      "password: const String.fromEnvironment('${_escape(input.passwordEnvironmentKey!)}')",
    if (input.sslEnabled) 'sslEnabled: true',
  ];

  return 'AnySqlConfig.${input.dialect.name}(\n'
      '          ${values.join(',\n          ')},\n'
      '        )';
}

String _escape(String value) {
  final buffer = StringBuffer();

  for (final codeUnit in value.codeUnits) {
    switch (codeUnit) {
      case 0x08:
        buffer.write(r'\b');
      case 0x09:
        buffer.write(r'\t');
      case 0x0A:
        buffer.write(r'\n');
      case 0x0B:
        buffer.write(r'\v');
      case 0x0C:
        buffer.write(r'\f');
      case 0x0D:
        buffer.write(r'\r');
      case 0x24:
        buffer.write(r'\$');
      case 0x27:
        buffer.write(r"\'");
      case 0x5C:
        buffer.write(r'\\');
      default:
        if (codeUnit < 0x20) {
          buffer.write(r'\x');
          buffer.write(codeUnit.toRadixString(16).padLeft(2, '0'));
        } else {
          buffer.writeCharCode(codeUnit);
        }
    }
  }

  return buffer.toString();
}

String _stringMapLiteral(Map<String, String> values) {
  if (values.isEmpty) {
    return 'const {}';
  }

  final entries = values.entries.map(
    (entry) => "'${_escape(entry.key)}': '${_escape(entry.value)}'",
  );
  return 'const {${entries.join(', ')}}';
}
