import 'anysql_config.dart';

final class AnySqlSetupInput {
  const AnySqlSetupInput({
    required this.dialect,
    required this.database,
    this.host,
    this.port,
    this.username,
    this.passwordEnvironmentKey,
    this.sslEnabled = false,
    this.backendUrl,
    this.backendHeaders = const {},
    this.className = 'DefaultAnySqlOptions',
  });

  final AnySqlDialect dialect;
  final String database;
  final String? host;
  final int? port;
  final String? username;
  final String? passwordEnvironmentKey;
  final bool sslEnabled;
  final String? backendUrl;
  final Map<String, String> backendHeaders;
  final String className;
}

String generateAnySqlOptionsFile(AnySqlSetupInput input) {
  final constructor = _configConstructor(input);
  final backendUri = input.backendUrl == null
      ? 'null'
      : "Uri.parse('${_escape(input.backendUrl!)}')";
  final backendHeaders = _stringMapLiteral(input.backendHeaders);

  return '''
// Generated by `dart run anysql configure`.
// Do not commit real database passwords. Prefer --password-env with --dart-define.

import 'package:anysql/anysql.dart';

final class ${input.className} {
  const ${input.className}._();

  static AnySqlOptions get current => AnySqlOptions(
        config: config,
        backendUri: backendUri,
        backendHeaders: backendHeaders,
      );

  static AnySqlConfig get config => $constructor;

  static Uri? get backendUri => $backendUri;

  static Map<String, String> get backendHeaders => $backendHeaders;

  static Future<AnySqlConnection> connect({
    required AnySqlDriver driver,
  }) {
    return current.connect(driver: driver);
  }

  static Future<AnySqlConnection> openWith(AnySql anySql) {
    return current.openWith(anySql);
  }

  static Future<AnySqlConnection> connectBackend({
    required AnySqlBackendClient client,
  }) {
    return current.connectBackend(client: client);
  }
}
''';
}

String generateAnySqlSampleOptionsFile({
  String className = 'AnySqlOptionsFile',
}) {
  return '''
// Generated by `dart run anysql init`.
// Replace these sample values with your own database or backend settings.
// Do not commit real database passwords. Prefer --dart-define values.

import 'package:anysql/anysql.dart';

final class $className {
  const $className._();

  static AnySqlOptions get postgres => AnySqlOptions(
        config: AnySqlConfig.postgres(
          host: 'localhost',
          port: 5432,
          database: 'postgres_database',
          username: 'postgres_user',
          password: const String.fromEnvironment('ANYSQL_POSTGRES_PASSWORD'),
          sslEnabled: false,
        ),
        backendUri: Uri.parse('https://api.example.com/anysql/postgres'),
        backendHeaders: const {'x-client': 'anysql-postgres'},
      );

  static AnySqlOptions get mysql => AnySqlOptions(
        config: AnySqlConfig.mysql(
          host: 'localhost',
          port: 3306,
          database: 'mysql_database',
          username: 'mysql_user',
          password: const String.fromEnvironment('ANYSQL_MYSQL_PASSWORD'),
          sslEnabled: false,
        ),
        backendUri: Uri.parse('https://api.example.com/anysql/mysql'),
        backendHeaders: const {'x-client': 'anysql-mysql'},
      );

  static AnySqlOptions get sqlite => AnySqlOptions(
        config: AnySqlConfig.sqlite(
          database: 'app_database.sqlite',
        ),
        backendUri: Uri.parse('https://api.example.com/anysql/sqlite'),
        backendHeaders: const {'x-client': 'anysql-sqlite'},
      );

  static AnySqlOptions get mongodb => AnySqlOptions(
        config: AnySqlConfig.mongodb(
          host: 'localhost',
          port: 27017,
          database: 'mongodb_database',
          username: 'mongodb_user',
          password: const String.fromEnvironment('ANYSQL_MONGODB_PASSWORD'),
          sslEnabled: false,
        ),
        backendUri: Uri.parse('https://api.example.com/anysql/mongodb'),
        backendHeaders: const {'x-client': 'anysql-mongodb'},
      );

  static Map<AnySqlDialect, AnySqlOptions> get all => {
        AnySqlDialect.postgres: postgres,
        AnySqlDialect.mysql: mysql,
        AnySqlDialect.sqlite: sqlite,
        AnySqlDialect.mongodb: mongodb,
      };

  static AnySqlOptions byDialect(AnySqlDialect dialect) {
    final options = all[dialect];
    if (options == null) {
      throw AnySqlException('No sample options for \${dialect.name}.');
    }

    return options;
  }
}
''';
}

String _configConstructor(AnySqlSetupInput input) {
  final values = switch (input.dialect) {
    AnySqlDialect.sqlite => <String>["database: '${_escape(input.database)}'"],
    AnySqlDialect.custom => <String>[
      'dialect: AnySqlDialect.custom',
      if (input.host != null) "host: '${_escape(input.host!)}'",
      if (input.port != null) 'port: ${input.port}',
      "database: '${_escape(input.database)}'",
      if (input.username != null) "username: '${_escape(input.username!)}'",
      if (input.passwordEnvironmentKey != null)
        "password: const String.fromEnvironment('${_escape(input.passwordEnvironmentKey!)}')",
      if (input.sslEnabled) 'sslEnabled: true',
    ],
    _ => <String>[
      if (input.host != null) "host: '${_escape(input.host!)}'",
      if (input.port != null) 'port: ${input.port}',
      "database: '${_escape(input.database)}'",
      if (input.username != null) "username: '${_escape(input.username!)}'",
      if (input.passwordEnvironmentKey != null)
        "password: const String.fromEnvironment('${_escape(input.passwordEnvironmentKey!)}')",
      if (input.sslEnabled) 'sslEnabled: true',
    ],
  };

  final constructor = input.dialect == AnySqlDialect.custom
      ? 'AnySqlConfig'
      : 'AnySqlConfig.${input.dialect.name}';

  return '$constructor(\n'
      '          ${values.join(',\n          ')},\n'
      '        )';
}

String _escape(String value) {
  final buffer = StringBuffer();

  for (final codeUnit in value.codeUnits) {
    switch (codeUnit) {
      case 0x08:
        buffer.write(r'\b');
      case 0x09:
        buffer.write(r'\t');
      case 0x0A:
        buffer.write(r'\n');
      case 0x0B:
        buffer.write(r'\v');
      case 0x0C:
        buffer.write(r'\f');
      case 0x0D:
        buffer.write(r'\r');
      case 0x24:
        buffer.write(r'\$');
      case 0x27:
        buffer.write(r"\'");
      case 0x5C:
        buffer.write(r'\\');
      default:
        if (codeUnit < 0x20) {
          buffer.write(r'\x');
          buffer.write(codeUnit.toRadixString(16).padLeft(2, '0'));
        } else {
          buffer.writeCharCode(codeUnit);
        }
    }
  }

  return buffer.toString();
}

String _stringMapLiteral(Map<String, String> values) {
  if (values.isEmpty) {
    return 'const {}';
  }

  final entries = values.entries.map(
    (entry) => "'${_escape(entry.key)}': '${_escape(entry.value)}'",
  );
  return 'const {${entries.join(', ')}}';
}
